// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: share.proto

package share

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PopularShareListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClickNum int32 `protobuf:"varint,1,opt,name=click_num,json=clickNum,proto3" json:"click_num,omitempty"`
}

func (x *PopularShareListRequest) Reset() {
	*x = PopularShareListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_share_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PopularShareListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopularShareListRequest) ProtoMessage() {}

func (x *PopularShareListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_share_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopularShareListRequest.ProtoReflect.Descriptor instead.
func (*PopularShareListRequest) Descriptor() ([]byte, []int) {
	return file_share_proto_rawDescGZIP(), []int{0}
}

func (x *PopularShareListRequest) GetClickNum() int32 {
	if x != nil {
		return x.ClickNum
	}
	return 0
}

type PopularShareListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*ShareBasicDetailReply `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *PopularShareListReply) Reset() {
	*x = PopularShareListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_share_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PopularShareListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopularShareListReply) ProtoMessage() {}

func (x *PopularShareListReply) ProtoReflect() protoreflect.Message {
	mi := &file_share_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopularShareListReply.ProtoReflect.Descriptor instead.
func (*PopularShareListReply) Descriptor() ([]byte, []int) {
	return file_share_proto_rawDescGZIP(), []int{1}
}

func (x *PopularShareListReply) GetList() []*ShareBasicDetailReply {
	if x != nil {
		return x.List
	}
	return nil
}

type ShareBasicDetailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identity string `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
}

func (x *ShareBasicDetailRequest) Reset() {
	*x = ShareBasicDetailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_share_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareBasicDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareBasicDetailRequest) ProtoMessage() {}

func (x *ShareBasicDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_share_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareBasicDetailRequest.ProtoReflect.Descriptor instead.
func (*ShareBasicDetailRequest) Descriptor() ([]byte, []int) {
	return file_share_proto_rawDescGZIP(), []int{2}
}

func (x *ShareBasicDetailRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type ShareBasicDetailReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identity           string `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	RepositoryIdentity string `protobuf:"bytes,2,opt,name=repository_identity,json=repositoryIdentity,proto3" json:"repository_identity,omitempty"`
	Name               string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Owner              string `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Avatar             string `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Ext                string `protobuf:"bytes,6,opt,name=ext,proto3" json:"ext,omitempty"`
	Size               int64  `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	Path               string `protobuf:"bytes,8,opt,name=path,proto3" json:"path,omitempty"`
	ClickNum           int32  `protobuf:"varint,9,opt,name=click_num,json=clickNum,proto3" json:"click_num,omitempty"`
	ExpiredTime        int32  `protobuf:"varint,10,opt,name=expired_time,json=expiredTime,proto3" json:"expired_time,omitempty"`
	Desc               string `protobuf:"bytes,11,opt,name=desc,proto3" json:"desc,omitempty"`
	UpdatedAt          string `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *ShareBasicDetailReply) Reset() {
	*x = ShareBasicDetailReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_share_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareBasicDetailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareBasicDetailReply) ProtoMessage() {}

func (x *ShareBasicDetailReply) ProtoReflect() protoreflect.Message {
	mi := &file_share_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareBasicDetailReply.ProtoReflect.Descriptor instead.
func (*ShareBasicDetailReply) Descriptor() ([]byte, []int) {
	return file_share_proto_rawDescGZIP(), []int{3}
}

func (x *ShareBasicDetailReply) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *ShareBasicDetailReply) GetRepositoryIdentity() string {
	if x != nil {
		return x.RepositoryIdentity
	}
	return ""
}

func (x *ShareBasicDetailReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShareBasicDetailReply) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ShareBasicDetailReply) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *ShareBasicDetailReply) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *ShareBasicDetailReply) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ShareBasicDetailReply) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ShareBasicDetailReply) GetClickNum() int32 {
	if x != nil {
		return x.ClickNum
	}
	return 0
}

func (x *ShareBasicDetailReply) GetExpiredTime() int32 {
	if x != nil {
		return x.ExpiredTime
	}
	return 0
}

func (x *ShareBasicDetailReply) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *ShareBasicDetailReply) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ShareStatisticsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShareStatisticsRequest) Reset() {
	*x = ShareStatisticsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_share_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareStatisticsRequest) ProtoMessage() {}

func (x *ShareStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_share_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareStatisticsRequest.ProtoReflect.Descriptor instead.
func (*ShareStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_share_proto_rawDescGZIP(), []int{4}
}

type ShareStatisticsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShareCount int32 `protobuf:"varint,1,opt,name=share_count,json=shareCount,proto3" json:"share_count,omitempty"`
	ClickNum   int32 `protobuf:"varint,2,opt,name=click_num,json=clickNum,proto3" json:"click_num,omitempty"`
}

func (x *ShareStatisticsReply) Reset() {
	*x = ShareStatisticsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_share_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareStatisticsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareStatisticsReply) ProtoMessage() {}

func (x *ShareStatisticsReply) ProtoReflect() protoreflect.Message {
	mi := &file_share_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareStatisticsReply.ProtoReflect.Descriptor instead.
func (*ShareStatisticsReply) Descriptor() ([]byte, []int) {
	return file_share_proto_rawDescGZIP(), []int{5}
}

func (x *ShareStatisticsReply) GetShareCount() int32 {
	if x != nil {
		return x.ShareCount
	}
	return 0
}

func (x *ShareStatisticsReply) GetClickNum() int32 {
	if x != nil {
		return x.ClickNum
	}
	return 0
}

type ShareBasicCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserIdentity           string `protobuf:"bytes,1,opt,name=user_identity,json=userIdentity,proto3" json:"user_identity,omitempty"`
	UserRepositoryIdentity string `protobuf:"bytes,2,opt,name=user_repository_identity,json=userRepositoryIdentity,proto3" json:"user_repository_identity,omitempty"`
	ExpiredTime            int32  `protobuf:"varint,3,opt,name=expired_time,json=expiredTime,proto3" json:"expired_time,omitempty"`
	Desc                   string `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
}

func (x *ShareBasicCreateRequest) Reset() {
	*x = ShareBasicCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_share_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareBasicCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareBasicCreateRequest) ProtoMessage() {}

func (x *ShareBasicCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_share_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareBasicCreateRequest.ProtoReflect.Descriptor instead.
func (*ShareBasicCreateRequest) Descriptor() ([]byte, []int) {
	return file_share_proto_rawDescGZIP(), []int{6}
}

func (x *ShareBasicCreateRequest) GetUserIdentity() string {
	if x != nil {
		return x.UserIdentity
	}
	return ""
}

func (x *ShareBasicCreateRequest) GetUserRepositoryIdentity() string {
	if x != nil {
		return x.UserRepositoryIdentity
	}
	return ""
}

func (x *ShareBasicCreateRequest) GetExpiredTime() int32 {
	if x != nil {
		return x.ExpiredTime
	}
	return 0
}

func (x *ShareBasicCreateRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type ShareBasicCreateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identity string `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Msg      string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Code     int32  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ShareBasicCreateReply) Reset() {
	*x = ShareBasicCreateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_share_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareBasicCreateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareBasicCreateReply) ProtoMessage() {}

func (x *ShareBasicCreateReply) ProtoReflect() protoreflect.Message {
	mi := &file_share_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareBasicCreateReply.ProtoReflect.Descriptor instead.
func (*ShareBasicCreateReply) Descriptor() ([]byte, []int) {
	return file_share_proto_rawDescGZIP(), []int{7}
}

func (x *ShareBasicCreateReply) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *ShareBasicCreateReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ShareBasicCreateReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type ShareBasicSaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserIdentity       string `protobuf:"bytes,1,opt,name=user_identity,json=userIdentity,proto3" json:"user_identity,omitempty"`
	RepositoryIdentity string `protobuf:"bytes,2,opt,name=repository_identity,json=repositoryIdentity,proto3" json:"repository_identity,omitempty"`
	ParentId           int64  `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
}

func (x *ShareBasicSaveRequest) Reset() {
	*x = ShareBasicSaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_share_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareBasicSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareBasicSaveRequest) ProtoMessage() {}

func (x *ShareBasicSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_share_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareBasicSaveRequest.ProtoReflect.Descriptor instead.
func (*ShareBasicSaveRequest) Descriptor() ([]byte, []int) {
	return file_share_proto_rawDescGZIP(), []int{8}
}

func (x *ShareBasicSaveRequest) GetUserIdentity() string {
	if x != nil {
		return x.UserIdentity
	}
	return ""
}

func (x *ShareBasicSaveRequest) GetRepositoryIdentity() string {
	if x != nil {
		return x.RepositoryIdentity
	}
	return ""
}

func (x *ShareBasicSaveRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

type ShareBasicSaveReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identity string `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Code     int32  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Msg      string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ShareBasicSaveReply) Reset() {
	*x = ShareBasicSaveReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_share_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareBasicSaveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareBasicSaveReply) ProtoMessage() {}

func (x *ShareBasicSaveReply) ProtoReflect() protoreflect.Message {
	mi := &file_share_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareBasicSaveReply.ProtoReflect.Descriptor instead.
func (*ShareBasicSaveReply) Descriptor() ([]byte, []int) {
	return file_share_proto_rawDescGZIP(), []int{9}
}

func (x *ShareBasicSaveReply) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *ShareBasicSaveReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ShareBasicSaveReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UserShareListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password     string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email        string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Code         string `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	UserIdentity string `protobuf:"bytes,5,opt,name=user_identity,json=userIdentity,proto3" json:"user_identity,omitempty"`
}

func (x *UserShareListRequest) Reset() {
	*x = UserShareListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_share_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserShareListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserShareListRequest) ProtoMessage() {}

func (x *UserShareListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_share_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserShareListRequest.ProtoReflect.Descriptor instead.
func (*UserShareListRequest) Descriptor() ([]byte, []int) {
	return file_share_proto_rawDescGZIP(), []int{10}
}

func (x *UserShareListRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserShareListRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserShareListRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserShareListRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UserShareListRequest) GetUserIdentity() string {
	if x != nil {
		return x.UserIdentity
	}
	return ""
}

type UserShareListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*ShareBasicDetailReply `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *UserShareListReply) Reset() {
	*x = UserShareListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_share_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserShareListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserShareListReply) ProtoMessage() {}

func (x *UserShareListReply) ProtoReflect() protoreflect.Message {
	mi := &file_share_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserShareListReply.ProtoReflect.Descriptor instead.
func (*UserShareListReply) Descriptor() ([]byte, []int) {
	return file_share_proto_rawDescGZIP(), []int{11}
}

func (x *UserShareListReply) GetList() []*ShareBasicDetailReply {
	if x != nil {
		return x.List
	}
	return nil
}

var File_share_proto protoreflect.FileDescriptor

var file_share_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x22, 0x36, 0x0a, 0x17, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x53,
	0x68, 0x61, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x22, 0x49, 0x0a, 0x15,
	0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x53, 0x68, 0x61, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x30, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x53, 0x68, 0x61, 0x72,
	0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x35, 0x0a, 0x17, 0x53, 0x68, 0x61, 0x72, 0x65,
	0x42, 0x61, 0x73, 0x69, 0x63, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0xd3,
	0x02, 0x0a, 0x15, 0x53, 0x68, 0x61, 0x72, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x12, 0x2f, 0x0a, 0x13, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f,
	0x72, 0x79, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x12, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e,
	0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x12, 0x21,
	0x0a, 0x0c, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x53, 0x68, 0x61, 0x72, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x54,
	0x0a, 0x14, 0x53, 0x68, 0x61, 0x72, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x68, 0x61, 0x72, 0x65, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x68, 0x61,
	0x72, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x63, 0x6b,
	0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x63,
	0x6b, 0x4e, 0x75, 0x6d, 0x22, 0xaf, 0x01, 0x0a, 0x17, 0x53, 0x68, 0x61, 0x72, 0x65, 0x42, 0x61,
	0x73, 0x69, 0x63, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x23, 0x0a, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x38, 0x0a, 0x18, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x72, 0x65,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12,
	0x21, 0x0a, 0x0c, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x22, 0x59, 0x0a, 0x15, 0x53, 0x68, 0x61, 0x72, 0x65, 0x42,
	0x61, 0x73, 0x69, 0x63, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x1a, 0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x22, 0x8a, 0x01, 0x0a, 0x15, 0x53, 0x68, 0x61, 0x72, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63,
	0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x12, 0x2f, 0x0a, 0x13, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x72,
	0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x57,
	0x0a, 0x13, 0x53, 0x68, 0x61, 0x72, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x53, 0x61, 0x76, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x95, 0x01, 0x0a, 0x14, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x68, 0x61, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22,
	0x46, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x53, 0x68, 0x61, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x30, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x53, 0x68, 0x61, 0x72,
	0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x32, 0xe1, 0x03, 0x0a, 0x05, 0x53, 0x68, 0x61, 0x72,
	0x65, 0x12, 0x50, 0x0a, 0x10, 0x53, 0x68, 0x61, 0x72, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1e, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x53, 0x68,
	0x61, 0x72, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x53, 0x68,
	0x61, 0x72, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x50, 0x0a, 0x10, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x53, 0x68,
	0x61, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1e, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e,
	0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x53, 0x68, 0x61, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e,
	0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x53, 0x68, 0x61, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4d, 0x0a, 0x0f, 0x53, 0x68, 0x61, 0x72, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x12, 0x1d, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e,
	0x53, 0x68, 0x61, 0x72, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x50, 0x0a, 0x10, 0x53, 0x68, 0x61, 0x72, 0x65, 0x42, 0x61, 0x73,
	0x69, 0x63, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4a, 0x0a, 0x0e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x42,
	0x61, 0x73, 0x69, 0x63, 0x53, 0x61, 0x76, 0x65, 0x12, 0x1c, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x53, 0x61, 0x76, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x53,
	0x68, 0x61, 0x72, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x47, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x53, 0x68, 0x61, 0x72, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x1b, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x68, 0x61, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x09, 0x5a, 0x07, 0x2e,
	0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_share_proto_rawDescOnce sync.Once
	file_share_proto_rawDescData = file_share_proto_rawDesc
)

func file_share_proto_rawDescGZIP() []byte {
	file_share_proto_rawDescOnce.Do(func() {
		file_share_proto_rawDescData = protoimpl.X.CompressGZIP(file_share_proto_rawDescData)
	})
	return file_share_proto_rawDescData
}

var file_share_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_share_proto_goTypes = []interface{}{
	(*PopularShareListRequest)(nil), // 0: share.PopularShareListRequest
	(*PopularShareListReply)(nil),   // 1: share.PopularShareListReply
	(*ShareBasicDetailRequest)(nil), // 2: share.ShareBasicDetailRequest
	(*ShareBasicDetailReply)(nil),   // 3: share.ShareBasicDetailReply
	(*ShareStatisticsRequest)(nil),  // 4: share.ShareStatisticsRequest
	(*ShareStatisticsReply)(nil),    // 5: share.ShareStatisticsReply
	(*ShareBasicCreateRequest)(nil), // 6: share.ShareBasicCreateRequest
	(*ShareBasicCreateReply)(nil),   // 7: share.ShareBasicCreateReply
	(*ShareBasicSaveRequest)(nil),   // 8: share.ShareBasicSaveRequest
	(*ShareBasicSaveReply)(nil),     // 9: share.ShareBasicSaveReply
	(*UserShareListRequest)(nil),    // 10: share.UserShareListRequest
	(*UserShareListReply)(nil),      // 11: share.UserShareListReply
}
var file_share_proto_depIdxs = []int32{
	3,  // 0: share.PopularShareListReply.list:type_name -> share.ShareBasicDetailReply
	3,  // 1: share.UserShareListReply.list:type_name -> share.ShareBasicDetailReply
	2,  // 2: share.Share.ShareBasicDetail:input_type -> share.ShareBasicDetailRequest
	0,  // 3: share.Share.PopularShareList:input_type -> share.PopularShareListRequest
	4,  // 4: share.Share.ShareStatistics:input_type -> share.ShareStatisticsRequest
	6,  // 5: share.Share.ShareBasicCreate:input_type -> share.ShareBasicCreateRequest
	8,  // 6: share.Share.ShareBasicSave:input_type -> share.ShareBasicSaveRequest
	10, // 7: share.Share.UserShareList:input_type -> share.UserShareListRequest
	3,  // 8: share.Share.ShareBasicDetail:output_type -> share.ShareBasicDetailReply
	1,  // 9: share.Share.PopularShareList:output_type -> share.PopularShareListReply
	5,  // 10: share.Share.ShareStatistics:output_type -> share.ShareStatisticsReply
	7,  // 11: share.Share.ShareBasicCreate:output_type -> share.ShareBasicCreateReply
	9,  // 12: share.Share.ShareBasicSave:output_type -> share.ShareBasicSaveReply
	11, // 13: share.Share.UserShareList:output_type -> share.UserShareListReply
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_share_proto_init() }
func file_share_proto_init() {
	if File_share_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_share_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PopularShareListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_share_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PopularShareListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_share_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareBasicDetailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_share_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareBasicDetailReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_share_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareStatisticsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_share_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareStatisticsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_share_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareBasicCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_share_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareBasicCreateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_share_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareBasicSaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_share_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareBasicSaveReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_share_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserShareListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_share_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserShareListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_share_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_share_proto_goTypes,
		DependencyIndexes: file_share_proto_depIdxs,
		MessageInfos:      file_share_proto_msgTypes,
	}.Build()
	File_share_proto = out.File
	file_share_proto_rawDesc = nil
	file_share_proto_goTypes = nil
	file_share_proto_depIdxs = nil
}
